### PR TITLE
Iox-#346 Add copyright header check

### PR DESCRIPTION
**Pull request by jpsamper2009**
## Details

- This PR uses [`ament_copyright`][ac] to check that all source files contain an appropriate copyright header
- Currently supported copyright headers can be found in the [`template` directory][td]
- If in the future we need a copyright header different from those provided by `ament_copyright`, we may need to create a small python package that extends the available copyright headers
- This PR also fixes certain copyright headers which had small typos which caused them to be flagged by the checker

[ac]: https://github.com/ament/ament_lint/tree/master/ament_copyright
[td]: https://github.com/ament/ament_lint/tree/master/ament_copyright/ament_copyright/template

### CODE REVIEW

**Comment by jpsamper2009** [comment]
@elBoberido I'm not sure where the ECA check is getting the .ai email address from... everything is set up with the gmail account and the commits are signed with the email account too...

**Comment by mossmaurice** [comment]
> @elBoberido I'm not sure where the ECA check is getting the .ai email address from... everything is set up with the gmail account and the commits are signed with the email account too...

Have you doubled checked the email field under accounts.eclipse.org -> My Profile -> Edit Profile -> Account settings -> Email address?

If this is the right email address, I'll open a support ticket at https://bugs.eclipse.org/bugs/ for you.

**Review by elfenpiff — DISMISSED** [review]

**Comment by elBoberido** [comment]
@jpsamper2009 I think I found the problem. This is what I see at a commit
```
 Juan Pablo Samper authored and jpsamper2009 committed 10 hours ago 
```
If you hover the symbols to the left of that message you also see two different icons. It seems `Juan Pablo Sampler` has the apex.ai email address and the eca check is towards the author, not the committer.

**Review by marthtz — APPROVED** [review]
Good to have this in place!

**Review by FerdinandSpitzschnueffler — DISMISSED** [review]

**Comment by jpsamper2009** [comment]
@elBoberido Well I feel dumb... now this should be ready.

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

**Review by elBoberido — APPROVED** [review]

**Review by mossmaurice — APPROVED** [review]

**Pull request merged**
